- name: reboot host
  sudo: yes
  command: shutdown -r now 'Ansible updates triggered'

- name: wait until host is rebooted
  sudo: yes
  local_action: wait_for
    host={{ ansible_ssh_host }}
    port={{ ansible_ssh_port | default(22) }}
    delay=30
